apiVersion: skaffold/v2beta29
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*.yaml
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: ticketing-dev-367104
  artifacts:
    - image: us.gcr.io/ticketing-dev-367104/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    - image: us.gcr.io/ticketing-dev-367104/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "**/*.js"
    - image: us.gcr.io/ticketing-dev-367104/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    - image: us.gcr.io/ticketing-dev-367104/orders
      context: order
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
