name: test-order
on:
  pull_request:
    paths:
      - 'order/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && npm install --global yarn && yarn install && yarn run test:ci
